### PR TITLE
Fixing fury-adapter-apib-serializer link

### PR DESCRIPTION
**Pull request by ianwalter**

### CODE REVIEW

**Comment by kylef** [comment]
Thanks @ianwalter Look's like CircleCI has an outtage and the CI build didn't run and thus I can't merge the PR as GitHub won't allow me. Are you able to perhaps rebase this on master and repush to hopefully trigger CI again.

**Comment by ianwalter** [comment]
Not sure why it's not working for me. Feel free to cherry pick the change and close this if necessary.

**Comment by pksunkara** [comment]
@ianwalter Can you force push again? I have fixed the issue in circleCI where fork PRs weren't enabled before.

**Comment by pksunkara** [comment]
Change your commit message to `fix(docs): fixing fury-adapter-apib-serializer link`

**Comment by ianwalter** [comment]
@pksunkara Should I add `docs` to the scope list?

**Comment by kylef** [comment]
Thanks again @ianwalter, apololgies that your first contribution here was so complex.

**Pull request merged**
