### PR TITLE
chore: Get ready for npm's RFC 10

### LINKED ISSUE #137: Get ready for npm's RFC 10
- specs: https://github.com/npm/rfcs/blob/latest/accepted/0010-monorepo-subdirectory-declaration.md
- how to implement it: https://github.com/zeit/now-builders/pull/185

### PR DESCRIPTION
**Pull request by pedrohbtp**
Closes #137

### CODE REVIEW

**Comment by pedrohbtp** [comment]
On the CI it is failing on the commitlint displaying the message:

```
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
✖   scope may not be empty [scope-empty]
```
I don't quite understand how commitlint works.
Could you explain what would be the expected commit format?
Thank you

**Comment by pksunkara** [comment]
Rename the commit to `chore(project): get ready for npm's RFC 10`

**Comment by pedrohbtp** [comment]
Thank you for the review and explanation.
Just changed the commit.

Great work with this repository from you guys.

**Comment by honzajavorek** [comment]
@pedrohbtp Thank you for the PR! 👍

**Pull request merged**
