### PR TITLE
chore: Moved to github ci

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by pksunkara** [comment]
@kylef Do you have any idea about docs failure? I couldn't get pipenv running locally.

**Comment by kylef** [comment]
> Do you have any idea about docs failure?

@pksunkara I think I've seen that exact problem before, and I think using an older Node (10) would solve it for the docs container. There was some compatibility issues with jsdoc (which upgrading breaks support for older Nodes too). We probably want to keep those node/pythons as close to what they are on readthedocs since that's where master doc builds will happen.

**Comment by kylef** [comment]
https://github.com/apiaryio/api-elements.js/pull/374 was it

**Comment by pksunkara** [comment]
@kylef Please review and merge.

**Pull request closed without merging**
