### PR TITLE
Handle header without value during serialization

### LINKED ISSUE #584: Error when using the cli
I installed the cli 
`npm install @apielements/cli
`
and trying to use the cli with the following syntax 

`fury --format text/vnd.apiblueprint swagger.yaml demo.apib
`

but I got this error.

```
Template render error: (/usr/local/lib/node_modules/@apielements/cli/node_modules/@apielements/apib-serializer/template.nunjucks) [Line 21, Column 63]
  Error: Unable to call `header["value"]["toValue"]`, which is undefined or falsey
    at Object._prettifyError (/usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:665:3)
    at Template.render (/usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/environment.js:550:10)
    at /usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/environment.js:364:27
    at createTemplate (/usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/environment.js:313:9)
    at handle (/usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/environment.js:325:11)
    at /usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/environment.js:337:9
    at next (/usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/lib.js:326:7)
    at Object.asyncIter (/usr/local/lib/node_modules/@apielements/cli/node_modules/nunjucks/src/lib.js:332:3)
```

### PR DESCRIPTION
**Pull request by kylef**
Fixes #584

This is caused by handling header's where the member element does not contain a value.

### CODE REVIEW

**Comment by moatazeldebsy** [comment]
Hi @opichals can you please review it, appreciate your help

**Review by opichals — APPROVED** [review]
Looks good! :rocket:

**Comment by moatazeldebsy** [comment]
Thank you @kylef for your help and how can I use the fix now shall I use the source or it will be released?

**Comment by kylef** [comment]
@moatazeldebsy I've created a release including this fix as [`@apielements/cli 0.10.3`](https://github.com/apiaryio/api-elements.js/releases/tag/%40apielements%2Fcli%400.10.3).

**Comment by moatazeldebsy** [comment]
Thanks a lot, @kylef really appreciate your help, I just have a question, our `openapi.yaml` file including multiple responses like this: 
```
examples:
                Existing customer:
                  value:
                    is_known: true
                    is_b2b_customer: false
                    has_social_login: false
                    has_password: true
                New customer:
                  value:
                    is_known: false
                    is_b2b_customer: false
                    has_social_login: false
                    has_password: false
```
, and when I use the tool it's converted only one example and I got this warning: 
`warning: 'Media Type Object' 'examples' only one example is supported, other examples have been ignored - line 49`
is this not supported for now? or will be added afterward?

**Comment by moatazeldebsy** [comment]
@kylef we need to convert the swagger file to apiary but with multiple example, can you help me to know which class or file we need to check for this purpose?

**Comment by kylef** [comment]
The multiple request/response pairs model in API Blueprint differs from OpenAPI (in terms of converting OpenAPI 3.x to API Blueprint). In API Blueprint, a transaction is described by describing a particular request which would cause a particular response. There is an example https://apiblueprint.org/documentation/examples/06-requests.html which indicates different request headers triggering different responses.

OpenAPI lacks this information because specific requests parameters are decouple from responses. We don't know which parameters (headers/query parameters), requestBody and security policies which are linked to a particular response body in terms of linking them up properly. For example, which inputs trigger "Existing customer" response vs which inputs trigger "New customer" response in the API.

The internal formats that the surrounding ecosystem in Apiary deals in [API Elements](https://apielements.org/en/latest/) models itself around the same semantics to API Blueprint which is why multiple examples are not yet supported in the OpenAPI parser. There are no short term plans to solve that.

**Pull request merged**
